[package]
name = "pulse-island"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
pulse-persistence = { path = "../../crates/pulse-persistence" }
pulse-win32-hwnd = { path = "../../crates/pulse-win32-hwnd" }
pulse-win32 = { path = "../../crates/pulse-win32" }
pulse-win32-link = { path = "../../crates/pulse-win32-link" }

[lints]
workspace = true
